// 아이디 체크 프로시저
CREATE OR REPLACE PROCEDURE ID_DUP_CHK
( V_ID IN MEMBER.USERID%TYPE,
  PR_RESULT OUT NUMBER)
  IS
  BEGIN
     SELECT COUNT(*) INTO PR_RESULT
     FROM MEMBER
     WHERE USERID = V_ID;
  END;
  /
  
// 컴파일 결과 확인

SET SERVEROUTPUT ON;

DECLARE
     RESULT NUMBER;
BEGIN
     ID_DUP_CHK('admina', RESULT);
     DBMS_OUTPUT.PUT_LINE('RESULT :: ' || RESULT);
END;
/